export const playListPart9 = [
  { id: 80, url: './assets/audio/Kimiko Itoh - Follow Me.mp3', name: 'Kimiko Itoh - Follow Me.mp3', cover: '', colorBaseColor: '20, 13%, 44%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 81, url: './assets/audio/Akira Yamaoka feat. Melissa Williamson (Mary Elizabeth McGlynn) - Room Of Angel .mp3', name: 'Akira Yamaoka feat. Melissa Williamson (Mary Elizabeth McGlynn) - Room Of Angel .mp3', cover: '', colorBaseColor: '340, 15%, 41%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 82, url: './assets/audio/Бах - Воздух (Оркестровая сюита N3 ре-мажор BWV 1068).mp3', name: 'Бах - Воздух (Оркестровая сюита N3 ре-мажор BWV 1068).mp3', cover: '', colorBaseColor: '320, 18%, 39%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 83, url: './assets/audio/Кукрыниксы - Падение.mp3', name: 'Кукрыниксы - Падение.mp3', cover: '', colorBaseColor: '300, 20%, 43%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 84, url: './assets/audio/Бетховен - Лунная соната. Часть 1- Adagio sostenuto.mp3', name: 'Бетховен - Лунная соната. Часть 1- Adagio sostenuto.mp3', cover: '', colorBaseColor: '280, 13%, 47%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 85, url: './assets/audio/Кукрыниксы - Моя свеча.mp3', name: 'Кукрыниксы - Моя свеча.mp3', cover: '', colorBaseColor: '260, 15%, 44%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 86, url: './assets/audio/Сплин - Небо в алмазах.mp3', name: 'Сплин - Небо в алмазах.mp3', cover: '', colorBaseColor: '240, 18%, 41%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 87, url: './assets/audio/Massive Attack, Portishead, Tricky - Black Milk.mp3', name: 'Massive Attack, Portishead, Tricky - Black Milk.mp3', cover: '', colorBaseColor: '220, 20%, 39%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 88, url: './assets/audio/Massive Attack - Atlas Air.mp3', name: 'Massive Attack - Atlas Air.mp3', cover: '', colorBaseColor: '200, 13%, 47%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 89, url: './assets/audio/Cafe Americaine - L\'amour.mp3', name: 'Cafe Americaine - L\'amour.mp3', cover: '', colorBaseColor: '180, 15%, 42%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
] 
