export const playListPart7 = [
  { id: 60, url: './assets/audio/Gavin Greenaway, The Lyndhurst Orchestra, Hans Zimmer, Lisa Gerrard, Djimon Houn.mp3', name: 'Gavin Greenaway, The Lyndhurst Orchestra, Hans Zimmer, Lisa Gerrard, Djimon Houn.mp3', cover: '', colorBaseColor: '80, 13%, 44%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 61, url: './assets/audio/Варвара Визбор - А зима будет большая.mp3', name: 'Варвара Визбор - А зима будет большая.mp3', cover: '', colorBaseColor: '60, 15%, 41%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 62, url: './assets/audio/Arash Safaian, Sebastian Knauer, Zürcher Kammerorchester - Una fantasia.mp3', name: 'Arash Safaian, Sebastian Knauer, Zürcher Kammerorchester - Una fantasia.mp3', cover: '', colorBaseColor: '40, 18%, 39%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 63, url: './assets/audio/Alfred Brendel - Beethoven_ Piano Sonata No. 14 in C-Sharp Minor, Op. 27 No. 2 M.mp3', name: 'Alfred Brendel - Beethoven_ Piano Sonata No. 14 in C-Sharp Minor, Op. 27 No. 2 M.mp3', cover: '', colorBaseColor: '20, 20%, 43%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 64, url: './assets/audio/Е.Дога - Вальс Из К_Ф Мой Ласковый И Нежный Зверь.mp3', name: 'Е.Дога - Вальс Из К_Ф Мой Ласковый И Нежный Зверь.mp3', cover: '', colorBaseColor: '340, 13%, 47%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 65, url: './assets/audio/Valdi Sabev - As the Rain (Original Mix) (1).mp3', name: 'Valdi Sabev - As the Rain (Original Mix) (1).mp3', cover: '', colorBaseColor: '320, 15%, 44%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 66, url: './assets/audio/Joe Hisaishi - Futatabi (OST Spirited Away).mp3', name: 'Joe Hisaishi - Futatabi (OST Spirited Away).mp3', cover: '', colorBaseColor: '300, 18%, 41%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 67, url: './assets/audio/Chris Wonderful feat. Maria Mena - Habits .mp3', name: 'Chris Wonderful feat. Maria Mena - Habits .mp3', cover: '', colorBaseColor: '280, 20%, 39%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 68, url: './assets/audio/Madonna - Paradise.mp3', name: 'Madonna - Paradise.mp3', cover: '', colorBaseColor: '260, 13%, 47%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 69, url: './assets/audio/Chris Rea - Nothing to Fear.mp3', name: 'Chris Rea - Nothing to Fear.mp3', cover: '', colorBaseColor: '240, 15%, 42%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
] 
