export const playListPart6 = [
  { id: 50, url: './assets/audio/Vangelis - La petite fille de la mer.mp3', name: 'Vangelis - La petite fille de la mer.mp3', cover: '', colorBaseColor: '280, 18%, 39%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 51, url: './assets/audio/Vangelis - West Across the Ocean Sea.mp3', name: 'Vangelis - West Across the Ocean Sea.mp3', cover: '', colorBaseColor: '260, 20%, 43%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 52, url: './assets/audio/Enigma - Sadeness Part I (Radio Edit) (320 kbps).mp3', name: 'Enigma - Sadeness Part I (Radio Edit) (320 kbps).mp3', cover: '', colorBaseColor: '240, 13%, 47%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 53, url: './assets/audio/Vangelis - Rachel\'s Song.mp3', name: 'Vangelis - Rachel\'s Song.mp3', cover: '', colorBaseColor: '220, 15%, 42%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 54, url: './assets/audio/Enigma - Shadows In Silence.mp3', name: 'Enigma - Shadows In Silence.mp3', cover: '', colorBaseColor: '200, 18%, 39%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 55, url: './assets/audio/Vangelis - Vangelis_ La petite fille de la mer.mp3', name: 'Vangelis - Vangelis_ La petite fille de la mer.mp3', cover: '', colorBaseColor: '180, 20%, 41%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 56, url: './assets/audio/Lisa Gerrard, Gavin Greenaway, The Lyndhurst Orchestra - Now We Are Free.mp3', name: 'Lisa Gerrard, Gavin Greenaway, The Lyndhurst Orchestra - Now We Are Free.mp3', cover: '', colorBaseColor: '160, 13%, 47%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 57, url: './assets/audio/Arash Safaian_Sebastian Knauer_Ludwig van Beethoven - Adagietto.mp3', name: 'Arash Safaian_Sebastian Knauer_Ludwig van Beethoven - Adagietto.mp3', cover: '', colorBaseColor: '140, 15%, 44%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 58, url: './assets/audio/Sarah Brightman - So many things.mp3', name: 'Sarah Brightman - So many things.mp3', cover: '', colorBaseColor: '120, 18%, 39%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 59, url: './assets/audio/Alexandra Stréliski - Concerto in D Minor (After Alessandro Marcello), BWV 974_ .mp3', name: 'Alexandra Stréliski - Concerto in D Minor (After Alessandro Marcello), BWV 974_ .mp3', cover: '', colorBaseColor: '100, 20%, 43%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
] 
