export const playListPart4 = [
  { id: 30, url: './assets/audio/StereOMantra - Magic Garden (Magic Garden, 2017, remastered).mp3', name: 'StereOMantra - Magic Garden (Magic Garden, 2017, remastered).mp3', cover: '', colorBaseColor: '340, 13%, 44%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 31, url: './assets/audio/Karunesh - Heaven & Earth.mp3', name: 'Karunesh - Heaven & Earth.mp3', cover: '', colorBaseColor: '320, 15%, 40%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 32, url: './assets/audio/Cafe Americaine - Rocket Design.mp3', name: 'Cafe Americaine - Rocket Design.mp3', cover: '', colorBaseColor: '300, 18%, 37%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 33, url: './assets/audio/Рок-опера Иисус Христос - Супер Звезда - 23.John Nineteen_ Forty-one (1970).mp3', name: 'Рок-опера Иисус Христос - Супер Звезда - 23.John Nineteen_ Forty-one (1970).mp3', cover: '', colorBaseColor: '280, 20%, 39%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 34, url: './assets/audio/The Sound Of Love - Magical Fly.mp3', name: 'The Sound Of Love - Magical Fly.mp3', cover: '', colorBaseColor: '260, 13%, 45%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 35, url: './assets/audio/Dj Artur - Dream of Elf.mp3', name: 'Dj Artur - Dream of Elf.mp3', cover: '', colorBaseColor: '240, 15%, 42%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 36, url: './assets/audio/Ария & Хелависа - Там высоко.mp3', name: 'Ария & Хелависа - Там высоко.mp3', cover: '', colorBaseColor: '220, 18%, 38%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 37, url: './assets/audio/Vangelis - Prelude & Losing Sleep (Still, My Heart).mp3', name: 'Vangelis - Prelude & Losing Sleep (Still, My Heart).mp3', cover: '', colorBaseColor: '200, 20%, 41%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 38, url: './assets/audio/Enigma - The Eyes Of Truth.mp3', name: 'Enigma - The Eyes Of Truth.mp3', cover: '', colorBaseColor: '180, 13%, 47%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
  { id: 39, url: './assets/audio/Enigma - The Rivers Of Belief .mp3', name: 'Enigma - The Rivers Of Belief .mp3', cover: '', colorBaseColor: '160, 15%, 43%', button: { url: '../assets/icons/btn-play-ghost.png', hue: '120deg' } },
] 
